config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'
  resources :users
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :questions do
    collection do
      get :solved
      get :unsolved
    end

    member do
      post :solve
    end

    resources :answers
  end

  resources :users, only: [:index]

  namespace :admin do
    resources :users, only: [:index, :destroy]
    resources :questions, only: [:index, :destroy]
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  validates :body, presence: true
  belongs_to :user
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
  scope :recent, -> { order(created_at: :desc) }
  belongs_to :user, optional: true
  has_many :answers, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_one_attached :image
  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  scope :related_to_question, ->(question) { joins(:answers).where(answers: { question_id: question.id }) }

  def mine?(object)
    object.user_id == id
  end
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < ApplicationController
  before_action :admin_required
  
  def index
    @q = Question.ransack(params[:q])
    @questions = @q.result(distinct: true).page(params[:page])
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to admin_questions_url, notice: "質問「#{@question.title}」を削除しました。"
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < ApplicationController
  skip_before_action :login_required

  def new
  end

  def create
    user = User.find_by(email: session_params[:email])
    if user&.authenticate(session_params[:password]) && user.admin
      session[:user_id] = user.id
      session[:user_admin] = user.id
      redirect_to  admin_questions_path, notice: "ログインしました"
    else
      render :new
    end
  end

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :admin_required

  def index
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true).page(params[:page])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_url, notice: "ユーザー「#{@user.name}」を削除しました。"
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    @answer = current_user.answers.new(answer_params.merge(question_id: params[:question_id]))
    if @answer.save
      unless current_user.mine?(@answer.question)
        QuestionMailer.with(user: @answer.question.user, question: @answer.question).answer_created.deliver_later
      end

      User.related_to_question(@answer.question).distinct.each do |user|
        next if user.id == current_user.id || user.mine?(@answer.question)

        AnswerMailer.with(user: user, question: @answer.question).answer_created.deliver_later
      end
      redirect_to question_url(params[:question_id]), notice: "回答しました"
    else
      @question = @answer.question
      @answers = Answer.where(question_id: @question.id).order(created_at: "DESC")
      flash.now[:danger] = "回答の作成に失敗しました"
      render 'questions/show'
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :login_required

  private

  def current_user
      @current_user　||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def login_required
    redirect_to login_url unless current_user
  end

  def admin_required
    redirect_to root_url unless session[:user_admin]
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, {only:[:edit, :update, :destroy]}

  def index
    @q = Question.ransack(params[:q])
    @questions = @q.result(distinct: true).order(created_at: :desc).page(params[:page])
  end

  def solved
    @q = Question.where(solved: true).ransack(params[:q])
    @questions = @q.result(distinct: true).order(created_at: :desc).page(params[:page])
    render :index
  end

  def unsolved
    @q = Question.where(solved: false).ransack(params[:q])
    @questions = @q.result(distinct: true).order(created_at: :desc).page(params[:page])
    render :index
  end

  def new
    @question = Question.new
  end

  def create
    @question = current_user.questions.new(question_params)
    if @question.save
      User.all.each { |user| QuestionMailer.with(user: user, question: @question).question_created.deliver_later }
      redirect_to question_url(@question), notice: "投稿「#{@question.title}」を追加しました。"
    else
      render :new
    end
  end

  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
    @answers = Answer.where(question_id: params[:id]).order(created_at: "DESC")
  end

  def edit
  end

  def update
    if @question.update(question_params)
      redirect_to question_url(@question), notice: "質問「#{@question.title}」を更新しました。"
    else
      flash.now[:danger] = "失敗しました"
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to questions_url, notice: "質問「#{@question.title}」を削除しました。"
  end

  def solve
    @question = current_user.questions.find(params[:id])
    @question.update!(solved: true)
    redirect_to question_path(@question), success: '解決済みにしました'
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end

  def set_question
    @question = current_user.questions.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required

  def new
  end

  def create
    user = User.find_by(email: session_params[:email])
    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to questions_url, notice: "ログインしました"
    else
      flash.now[:danger] = "ログインに失敗しました"
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to  login_url, notice: "ログアウトしました。"
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to questions_url, notice: "サインアップが完了しました"
    else
      flash.now[:danger] = "サインアップに失敗しました"
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:image, :name, :email, :password, :password_confirmation)
  end
end

app/helpers/admin/questions_helper.rb
module Admin::QuestionsHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/questions/index.html.slim
h1 質問一覧(管理者画面)

= search_form_for @q, url: admin_questions_path, class: 'mb-5' do |f|
  .form-group.row
    = f.label :title_cont, '検索機能', class: 'col-form-label'
    .col-sm-10
      = f.search_field :title_cont, class: 'form-control'
  .form-group
    = f.submit '検索', class: 'btn btn-outline-primary'

.mb-3
  = paginate @questions
  = page_entries_info @questions
table.table.table-hover
  thred.thred-default
    tr
      th= Question.human_attribute_name(:image)
      th= sort_link(@q, :title)
      th
  tbody
    - @questions.each do |question|
      tr
        td= image_tag question.user.image, width: '40', height: '40', class: 'img-responsive' if question.user.image.attached?
        td= question.title
        td= link_to '削除', admin_url(question), method: :delete, data: { confirm: "質問「#{question.title}」を削除します。よろしいですか？"}, class: 'btn btn-danger'

app/views/admin/users/index.html.slim
h1 ユーザー一覧(管理者画面)

= search_form_for @q, url: admin_users_path, class: 'mb-5' do |f|
  .form-group.row
    = f.label :name_cont, '検索機能', class: 'col-form-label'
    .col-sm-10
      = f.search_field :name_cont, class: 'form-control'
  .form-group
    = f.submit '検索', class: 'btn btn-outline-primary'

.mb-3
  = paginate @users
  = page_entries_info @users
table.table.table-hover
  thred.thred-default
    tr
      th= User.human_attribute_name(:image)
      th= sort_link(@q, :user_name)
      th
  tbody
    - @users.each do |user|
      tr
        td= image_tag user.image, width: '40', height: '40', class: 'img-responsive' if user.image.attached?
        td= user.name
        td
          = link_to '削除', admin_url(user), method: :delete, data: { confirm: "ユーザー「#{user.name}」を削除します。よろしいですか？"}, class: 'btn btn-danger'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | QuestionApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body

    .app-title.navbar.navbar-expand-md.navbar-light.bg-light
      .navbar-brand QuestionApp

      ul.navbar-nav.ml-auto
        - unless session[:user_admin]
          - if current_user
            li.nav-item= image_tag current_user.image, width: '40', height: '40', class: 'img-responsive' if current_user.image.attached?
            li.nav-item= link_to '質問一覧', questions_path, class: 'nav-link'
            li.nav-item= link_to 'ユーザー一覧', users_path, class: 'nav-link'
            li.nav-item= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link'
          - else
            li.nav-item= link_to 'ログイン', login_path, class: 'nav-link'
            li.nav-item= link_to '新規登録', new_user_path, class: 'nav-link'
        - else session[:user_admin]
            li.nav-item= image_tag current_user.image, width: '40', height: '40', class: 'img-responsive' if current_user.image.attached?
            li.nav-item= link_to '質問一覧（管理者画面）', admin_questions_path, class: 'nav-link'
            li.nav-item= link_to 'ユーザー一覧（管理者画面）', admin_users_path, class: 'nav-link'
            li.nav-item= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link'
    .container
      - if flash.notice.present?
        .alert.alert-success= flash.notice
    = yield

app/views/questions/edit.html.slim
h1 質問編集

= form_with model: [@question], local: true do |f|
  .form-group
    = f.label :title, '質問タイトル'
    = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :body, '質問内容'
    = f.text_area :body, class: 'form-control'
  = f.submit '投稿', class: 'btn btn-primary'

app/views/questions/index.html.slim
h1 質問一覧

nav-item= link_to '全て', questions_path, class: 'btn btn-primary'
nav-item= link_to '未解決', unsolved_questions_path, class: 'btn btn-primary'
nav-item= link_to '解決済み', solved_questions_path, class: 'btn btn-primary'

= search_form_for @q, url: questions_path, class: 'mb-5' do |f|
  .form-group.row
    = f.label :title_cont, '検索機能', class: 'col-form-label'
    .col-sm-10
      = f.search_field :title_cont, class: 'form-control'
  .form-group
    = f.submit '検索', class: 'btn btn-outline-primary'

= link_to '新規投稿', new_question_path, class: 'btn btn-primary'

.mb-3
  = paginate @questions
  = page_entries_info @questions
table.table.table-hover
  thred.thred-default
    tr
      th= Question.human_attribute_name(:image)
      th= sort_link(@q, :title)
      th= Question.human_attribute_name(:created_at)
  tbody
    - @questions.each do |question|
      tr
        td= image_tag question.user.image, width: '40', height: '40', class: 'img-responsive' if question.user.image.attached?
        td= link_to question.title, question
        td= question.created_at

app/views/questions/new.html.slim
h1 新規投稿

= form_with model: [@question], local: true do |f|
  .form-group
    = f.label :title, '質問タイトル'
    = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :body, '質問内容'
    = f.text_area :body, class: 'form-control'
  = f.submit '投稿', class: 'btn btn-primary'

app/views/questions/show.html.slim
h1 質問詳細

table.table.table-hover
  tbody
    tr
      th= User.human_attribute_name(:image)
      td= image_tag @question.user.image, width: '40', height: '40', class: 'img-responsive' if @question.user.image.attached?
    tr
      th= Question.human_attribute_name(:title)
      td= @question.title
    tr
      th= Question.human_attribute_name(:body)
      td= simple_format(h(@question.body),{}, sanitize: false, wrapper_tag: "div")

    - if @question.solved?
      tr
        th=
        td= "解決済み"
    - else
      tr
        th=
        td= "未解決"

- if current_user.id == @question.user_id
  = link_to '編集', edit_question_path, class: 'btn btn-primary mr-3'
  = link_to '削除', @question, method: :delete, data: { confirm: "質問「#{@question.title}」を削除します。よろしいですか？"}, class: 'btn btn-danger'
  - unless @question.solved?
    = link_to '解決済みにする', solve_question_path(@question), class: 'btn btn-primary mr-3', method: :post, data: { confirm: '解決済みにしますか' }


- unless current_user.id == @question.user_id
  = form_with model: [@question, @answer], local: true do |f|
    .form-group
      = f.label :body, '回答内容'
      = f.text_area :body, class: 'form-control'
    = f.submit '回答する', class: 'btn btn-primary'

.mb-3
table.table.table-hover
  thred.thred-default
  tbody
    - @answers.each do |answer|
      tr
        td= image_tag answer.user.image, width: '40', height: '40', class: 'img-responsive' if answer.user.image.attached?
        td= answer.body

app/views/users/index.html.slim
h1 ユーザー一覧

.mb-3
table.table.table-hover
  thred.thred-default

  tbody
    - @users.each do |user|
      tr
        td= image_tag user.image, width: '40', height: '40', class: 'img-responsive' if user.image.attached?
        td= user.name

app/views/users/new.html.slim
h1 ユーザー登録

= form_with model: [@user], local: true do |f|
  .form-group
    = f.label :image, '画像'
    = f.file_field :image, class: 'form-control'
  .form-group
    = f.label :name, '名前'
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :email, 'メールアドレス'
    = f.text_field :email, class: 'form-control'
  .form-group
    = f.label :password, 'パスワード'
    = f.password_field :password, class: 'form-control'
  .form-group
    = f.label :password_confirmation, 'パスワード（確認）'
    = f.password_field :password_confirmation, class: 'form-control'
  = f.submit '登録', class: 'btn btn-primary'